import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Box overlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Demo Overlap Box</h1>
        <section>
          <h2>About this project</h2>
          <p>
            A simple application made with React (NextJs) and local storage. The
            user can open the application in multiple tabs and move the box
            around. The box will be visible in all tabs.
          </p>
          <p>
            Github Repo:
            <Link
              href="https://github.com/quocbao19982009/BoxOverLap"
              rel="noopener noreferrer"
              target="_blank"
            >
              https://github.com/quocbao19982009/BoxOverLap
            </Link>
          </p>
          <p>
            Linkedin:{" "}
            <Link
              href="https://www.linkedin.com/in/bao-nguyen-dev/"
              rel="noopener noreferrer"
              target="_blank"
            >
              https://www.linkedin.com/in/bao-nguyen-dev/
            </Link>
          </p>
        </section>
        <section>
          <h3> How to use:</h3>
          <p>Open different boxes in separate tabs:</p>
          <p>
            Tab 1:{" "}
            <Link href="/local/1" rel="noopener noreferrer" target="_blank">
              {" "}
              local/1
            </Link>
          </p>
          <p>
            Tab 2:{" "}
            <Link href="/local/2" rel="noopener noreferrer" target="_blank">
              {" "}
              local/2
            </Link>
          </p>
          <p>
            Tab 3:{" "}
            <Link href="/local/3" rel="noopener noreferrer" target="_blank">
              {" "}
              local/3
            </Link>
          </p>
        </section>
      </main>
    </>
  );
}
